### ISSUE TITLE
non-Latin characters are changed in wp_trend

### ISSUE THREAD

**Issue by erzk** [petermeissner/wikipediatrend#12]
There is an issue when wp_trend is dealing with non-Latin characters.
 
I tried querying Wikipedia using the following code:
```
bkomo <- wp_trend(  page      = "Bronisław Komorowski", 
                  from      = "2015-01-01", 
                  lang      = "pl", 
                  friendly  = T, 
                  userAgent = T)
 ```
wp_trend seems to struggle with ‘ł’ and turns it into ‘l’ which brings irrelevant values.

**Comment by petermeissner** [comment]
Thanks for reporting!

Try using the exact title given in the URL of the Wikipedia article as argument to page ... 

```r
(wp_trend("Bronisław Komorowski")) # does not work
(wp_trend("Bronisław_Komorowski")) # does work
```
... to get data.

This does not prevent the `ł` from getting lost, however. 

```r
WP <- wp_trend("Bronisław_Komorowski")
WP 
##          date count lang                 page rank  month
## 1  2015-04-04     8   en Bronislaw_Komorowski   -1 201504
## 2  2015-04-05     8   en Bronislaw_Komorowski   -1 201504
## 3  2015-04-06     5   en Bronislaw_Komorowski   -1 201504
## 4  2015-04-07     9   en Bronislaw_Komorowski   -1 201504
## 5  2015-04-08    12   en Bronislaw_Komorowski   -1 201504
## 6  2015-04-09    15   en Bronislaw_Komorowski   -1 201504
## 7  2015-04-10    16   en Bronislaw_Komorowski   -1 201504
## ...


WP$page
##  [1] "Bronislaw_Komorowski" "Bronislaw_Komorowski" "Bronislaw_Komorowski" 
##  [4] "Bronislaw_Komorowski" "Bronislaw_Komorowski" "Bronislaw_Komorowski" ...
```

I presume you are using some Windows? I will have to dig deeper into that together with the other encoding/special character problems. 

It might be the case - if you use e.g. a Polish Windows - that while the print of the data frame looks wrong the actual correct information is entailed within the page column - just an idea that I cannot test because I only have an German version.

**Comment by erzk** [comment]
I'm running Windows 7 Ultimate (English) but I changed the keyboard settings.
I tried running this code with a keyboard set to both Polish and English but the result is the same.

**Comment by petermeissner** [comment]
I have done some major rewrites this week and special characters - in general - should be no problems . 

In your case however the problem seems to be with R itself. Whenever I try to do something with `ł`
it completely does not work at all. R simply discards the character although it works with all the other special characters. 

To get real counts non the less you can url-encode / percent-encode the title and use it as page-parameter:

```r
wp_trend("Bronis%C5%82aw_Komorowski", lang="en")
wp_trend("Bronis%C5%82aw_Komorowski", lang="pl")
```

**Comment by erzk** [comment]
It works like a charm. Thanks.

**Comment by petermeissner** [comment]
Thanks for testing, have fun.

**Comment by petermeissner** [comment]
I submitted a bug report to the R-developer-team though there will be no fix for Windows soon except

1) try using Polish Windows or set correct encoding in R
2) do not use Windows but Mac/OS or some Linux (I have tested with Ubuntu 14.04 LTS and the issues does not exist there)

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16377

**Comment by erzk** [comment]
Cheers, I'll try on Ubuntu.
