### ISSUE TITLE
Could not extract data from server response. Data for one month will be missing.

### ISSUE THREAD

**Issue by ThomasWilli** [petermeissner/wikipediatrend#23]
I try to download some Info, which usually workes great (thx, btw). However, there's a new Errormessage:

    http://stats.grok.se/json/fr/201510/Pascale_Bruderer
    Warning message:
    In value[[3L]](cond) : [wp_jsons_to_df()]
    Could not extract data from server response. Data for one month will be missing.

I updated rvest and wikipediatrend, but the error remains...

    library(wikipediatrend)
    wp_trend(page= "Pascale_Bruderer", 
                         lang= "fr",
                         from= "2015-10-10",  
                         to= "2015-10-10",
                         file="test.csv")

     session.Info()
     R version 3.2.2 (2015-08-14)
     Platform: x86_64-redhat-linux-gnu (64-bit)
     Running under: CentOS release 6.7 (Final)

    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

     attached base packages:
     [1] stats     graphics  grDevices utils     datasets  methods   base     

     other attached packages:
     [1] wikipediatrend_1.1.7

     loaded via a namespace (and not attached):
     [1] httr_1.0.0       R6_2.1.1         magrittr_1.5     tools_3.2.2      rstudioapi_0.3.1 RCurl_1.95-4.7  
     [7] curl_0.9.3       stringi_0.5-5    jsonlite_0.9.16  stringr_1.0.0    bitops_1.0-6

**Comment by petermeissner** [comment]
The error indicates that there were problems parsing the data which is most likely the case when data provided by the server simply is bad / unparsable  / non existing.  

I will have a closer look later on.

**Comment by ThomasWilli** [comment]
Perfect, thanks. Yesterday, the data was there...

**Comment by petermeissner** [comment]
I have looked into it and could replicate it some times and I could not replicate it other times without seeing what exactly the problem is. 

### Anyways ... 

- the warning comes up when there are problems parsing the data coming from the server
- this is most likely for data of the current month  (that is why `wp-trend()` is by default set to only retrieve data from the last month / up to the last month)
- it usually takes two or three days for the the data of a finished month to settle and become stable 

### Advice ... 

- if you are annoyed by the warnings use: `suppressWarnings( wp_trend(...) )`
- if the warning pops up you will still get as much data as there is for the page / time-frame requested stemming from both the data downloaded and the data within the current cache (in-memory / specific file / global file) so always use (as e.g. in your exampe post) as cache file to get at least the data downloaded some previous time

**Comment by ThomasWilli** [comment]
Ok, thanks a lot for the Info!

**Comment by petermeissner** [comment]
I pushed  version 1.1.8 of wikipediatrend to Github which now gives back the raw data retrieved by server if is cannot parse its content - while this does not change anything in regard to the results it might help diagnosing if wikipediatrend or the server response is misbehaving.

**Comment by ThomasWilli** [comment]
Thanks, I'm gonna update and try asap.
