### ISSUE TITLE
"to" date specification

### ISSUE THREAD

**Issue by akitepowell** [petermeissner/wikipediatrend#26]
I've been exploring your wikipediatrends R package, and have found that it doesn't appear to matter if I specify a "to" date in the code.  Am I doing something incorrectly?  When I run the code below it only retrieves data to sometime in January 2016.  Are there data available past that date?

For example:
cryptowiki <-
  wp_trend(
    page = "Cryptosporidium",
    from = "2015-01-01",
    to = "2016-09-03")
ggplot(cryptowiki, aes(x=date, y=count, group=page, color=page)) +
  geom_line(size=1) + theme_bw()+
  scale_x_date(breaks=date_breaks("1 month"))+
  theme(axis.text.x=element_text(angle=-90,size=rel(0.7)))+
  labs(x = "Date", y = "Frequency",title = "Wikipeida Search Volume for Cryptosporidiosis")

**Comment by petermeissner** [comment]
I am sorry for the inconvenience. This is something like a known issue ...

The stats.grok.se server to which the package connects does not provide new data any more since start of 2016 and since Wikipedia provides this data elsewhere. 

To get newer data check out the pageviews package: https://cran.r-project.org/web/packages/pageviews/index.html

There is a loose plan in my mind to combine both data sources within the wikipediatrend package but I do not know when I will start to work on that.

**Comment by akitepowell** [comment]
Ok, I see.  I'll give the other package a try too.  Thank you.

**Comment by petermeissner** [comment]
From Version 2.x.x  *wikipediatrend* uses the new API as data source (which provides data from mid 2015 onwards).
