### ISSUE TITLE
wp_linked_pages generates an internal error if there are no linked pages

### ISSUE THREAD

**Issue by alanault** [petermeissner/wikipediatrend#27]
Hi Peter,

Really enjoying the package and the ability to access the historical page views.

I found that if I use wp_linked_pages to find other language pages, on a page which doesn't have any, an internal error is generated.

e.g.
```wikipediatrend::wp_linked_pages("Sheerness_Lifeboat_Station", lang="en")```

The error message is:
```
Error in `[<-.data.frame`(`*tmp*`, lang_df$lang == "x-default", , value = c("Sheerness_Lifeboat_Station",  : 
  replacement has 2 rows, data has 0
```

Thought perhaps would be useful to know, in case you want to adapt to return a more informational warning message?

Thanks

Alan

**Comment by petermeissner** [comment]
Hey, thanks. 

That really is not very informative, especially since the page https://de.wikipedia.org/wiki/Sheerness_Lifeboat_Station does exist. The pages only fault is to not have any different language siblings. The function should handle those scenarios  by giving back a zero line data.frame. 

I will patch this.
