### ISSUE TITLE
Missing data from stats.grok.se

### ISSUE THREAD

**Issue by reisfe** [petermeissner/wikipediatrend#9]
I just noticed that for the months 2008.01 and 2008.07 stats.grok.se does not return data for several days (1 day in the case of 2008.01 and 21 days for 2008.07). I checked the wikipedia pagecounts dump files and they exist.
Right now, wikipediatrend keeps downloading those months even if data have been fetched before because it detects some days missing. This is the right behaviour if this problem with stats.grok.se is temporary. If this is a permanent problem then wikipediatrend should flag this somehow and not download it again.

**Comment by petermeissner** [comment]
I agree, that is indeed a problem but I, at the moment would opt for not solving it because there is no good solution ... 

default behaviour: 

1) wptrend assumes that all dates should have data, if not it tries to get the data again 
2) there is missing data due to the fact that data of current months is always incomplete and stats.grok.se also seems to lack behind up to 2 days
3) if you request data in June and cache it, than come back in August wptrend will download the new months as well as june because june has missing data

--> for that default scenario everything makes sense and works as it should


missing data problem:

1) in addition to the current-month problem there is the problem data simply missing although there is a valid date
2) due to the default sceanrio and its solution, here the download-agian procedure gets kicked in everytime


While I see the problem I do not see an immeadiate and smooth way to distinguish missing-missing data from current-date-missing data. That is basically why I, at the moment would opt for staying with the conservative solution of redownloading data if something is missing.

**Comment by petermeissner** [comment]
With the new persistent cache (within temp directory or specified by user) that allows for saving multiple pages with differing language in just one file the user might herself take care of excluding those months from the re-download while the package behavior stays conservative and predictable.
